import type { SkillTestBundle } from './types';
import { x, sa, o, sc } from './types';

// Core statements and their tips live in one table so the two stay in the same order.
const CORE: { d: string; text: string; tip: string; reverse?: boolean }[] = [
  { d: 'setbacks', text: 'Within a day or two of a bad result or a rejection, I can name one thing I will do next.', tip: 'Give yourself a fixed window, such as the rest of the evening, to feel upset. Next morning, write one next step on paper and do it before anything else.' },
  { d: 'mindset', text: 'I believe I can get much better at things I am weak at if I practise in the right way.', tip: 'Pick one weak skill and write down what better would look like in four weeks, such as three clear sentences in English or five solved problems without help. Then check it on the date.' },
  { d: 'effort', text: 'When a task turns boring or difficult, I keep going for a set time before deciding to stop.', tip: 'Set a timer for 25 minutes the next time you want to quit. Only after the timer ends may you decide whether to continue, switch method or stop.' },
  { d: 'learn', text: 'After a mistake, I write down one thing I will do differently next time.', tip: 'Keep a small mistakes page. For each error write what happened, why, and one changed action, and read the page before your next attempt.' },
  { d: 'drive', text: 'I can explain in one sentence why my current goal matters to me, apart from what others expect.', tip: 'Finish this sentence in writing: I want this because... If the only reason is family or friends, spend this week talking to one person doing this work and look for a reason of your own.' },
  { d: 'setbacks', text: 'A single failure makes me doubt whether I should continue with the whole goal.', reverse: true, tip: 'Separate the event from the goal. Write what the failure was about, such as method, preparation or timing, and change only that part before deciding about the whole goal.' },
  { d: 'mindset', text: 'I think some people are simply born good at things and I am not one of them.', reverse: true, tip: 'Ask someone who is good at the thing how they began and how long they took to improve. Many good performers can describe a clumsy start, and hearing it makes the gap look more like practice than talent.' },
  { d: 'effort', text: 'I often leave a hard task half finished and move to something easier.', reverse: true, tip: 'Write the hard task as the first item of the day and do 30 minutes on it before opening anything easier. Cross it off only when that block is done.' },
  { d: 'learn', text: 'I feel defensive when someone points out an error in my work.', reverse: true, tip: 'When you receive a correction, say thank you, repeat it in your own words and ask for one example. Decide later, in private, which parts to use.' },
  { d: 'drive', text: 'My effort drops sharply when nobody is checking my work.', reverse: true, tip: 'Create your own check: at the end of each study or work day, write three lines on what you finished. A visible record gives you something to look at when nobody else is checking.' },
  { d: 'setbacks', text: 'When something goes wrong, I look for the part I can still change.', tip: 'Draw two columns, can change and cannot change, the next time something goes wrong. Spend your next hour only on the first column.' },
  { d: 'mindset', text: 'When I see someone doing better than me, I ask what they did to get there.', tip: 'Choose one person who is ahead of you in something and ask them two questions: what did you practise, and what did you get wrong at first. Note the answers.' },
  { d: 'effort', text: 'I break a long goal into weekly pieces and keep going even when progress feels slow.', tip: 'Cut your goal into four weekly targets you can tick off, such as two chapters or ten applications. Review on the same day each week and adjust the next week only.' },
  { d: 'learn', text: 'I ask for feedback on my work from someone more experienced than me.', tip: 'Choose one piece of finished work and send it to a senior, teacher or mentor with one specific question, such as what is the weakest part. Specific questions get replies.' },
  { d: 'setbacks', text: 'I replay a setback in my head for days and find it hard to start the next task.', reverse: true, tip: 'Write the setback on paper in five lines, then close the page and start a very small next task for ten minutes. Writing it down can make it feel smaller, and a small task gives you a way back into work.' },
  { d: 'mindset', text: 'When I struggle with a skill, I decide on one thing to practise instead of deciding it is not for me.', tip: 'The next time you think I am not good at this, add the word yet and name one drill you will do three times this week. The word only helps if a practice step follows.' },
  { d: 'effort', text: 'I give up quickly if I do not see results within the first few days.', reverse: true, tip: 'Decide before you start how long a fair trial is, such as three weeks of daily practice, and write it down. Judge only at the end of that period, not on day three.' },
  { d: 'learn', text: 'I hide my mistakes instead of talking about them.', reverse: true, tip: 'Tell one trusted person about one recent mistake this week, in two sentences: what happened and what you changed. It is much easier to fix a mistake once someone else knows.' },
  { d: 'drive', text: 'When my motivation is low, I have a small routine that gets me started anyway.', tip: 'Design a five-minute starter, such as opening your notes, laying out your books or writing the first line, and do it at the same time and place daily. Once you have started, carrying on is often easier.' },
  { d: 'setbacks', text: 'When I am struggling, I tell someone I trust instead of carrying it alone.', tip: 'Pick one person, such as a parent, friend, teacher or senior, and tell them in three lines what is hard right now and what kind of help you want: advice, practice together or just listening.' },
  { d: 'mindset', text: 'I avoid tasks where I might look weak in front of others.', reverse: true, tip: 'Choose one low-risk place to be a beginner this month, such as a small group, a friend or an online practice group, and do one attempt there, however clumsy.' },
  { d: 'effort', text: 'I can practise something difficult for 30 to 45 minutes without picking up my phone.', tip: 'Put your phone in another room for one session a day and use a paper timer or watch. Increase the block by five minutes every few days.' },
  { d: 'learn', text: 'After a failure, I have changed my method and tried again.', tip: 'After the next failure, change exactly one thing, such as the time of study, the resource or the practice format, and write down what you changed so you can see if it helped.' },
  { d: 'drive', text: 'I often change my goal when a new idea looks more exciting.', reverse: true, tip: 'When a new idea appears, write it in a parked ideas list and wait one week before acting. If it still looks better after finishing your current review point, then switch deliberately.' },
];

export const bundle: SkillTestBundle = {
  test: {
    id: 'resilience-and-growth-mindset-assessment',
    slug: 'resilience-and-growth-mindset-assessment',
    pageUrl: '/services/assessments/resilience-and-growth-mindset-assessment/',
    breadcrumbName: 'Resilience and Growth Mindset Assessment',
    metaTitle: 'Resilience and Growth Mindset Test | Free Self-Assessment',
    metaDescription:
      'Free resilience and growth mindset self-assessment: 40 questions and five scores for setbacks, mindset, effort, learning from mistakes and drive. Instant result.',
    h1Lead: 'Resilience and Growth Mindset',
    h1Accent: 'Assessment',
    eyebrow: 'Setbacks, effort and learning in one report',
    heroSub:
      'Low marks, backlogs, rejections, layoffs and long plateaus test everyone. This free self-assessment turns resilience and a growth mindset into five concrete areas, bouncing back, belief that ability can grow, staying with hard tasks, using feedback and mistakes, and drive over time, and shows which one to build first.',
    stats: [
      { value: '40', label: 'questions' },
      { value: '5', label: 'areas' },
      { value: 'Free', label: 'PDF report' },
    ],
    main: 'picker',
    mainChecks: [
      'Five resilience and mindset areas from your own ratings',
      'About 7 minutes',
      'Where to build first, with a two-week plan',
    ],
    reportTitle: 'Resilience and Growth Mindset Report',
    reportFile: 'future-career-school-resilience-growth-mindset-report.pdf',
    reportKicker: 'RESILIENCE AND GROWTH MINDSET REPORT',
    resultKicker: 'Your resilience and growth mindset result',
    scoreLabel: 'Overall resilience and growth mindset',
    bands: {
      high: 'A relative strength.',
      mid: 'Developing, with room to grow.',
      low: 'This area needs the most work.',
    },
    domainsHeading: 'Five resilience and growth mindset areas this self-assessment covers',
    domainsIntro:
      'These areas describe what people do after a bad result, when a task gets hard, and when feedback arrives. Each one is written as an everyday habit you can rate honestly and practise.',
    domains: [
      {
        key: 'setbacks',
        name: 'Bouncing back from setbacks',
        short: 'Recovering after a failure or rejection',
        strong: 'You feel the disappointment, reach out when you need support, and move to a next step without losing weeks to it.',
        weak: 'A bad result stays with you for a long time, you carry it alone, or one failure makes you doubt the whole goal.',
        plan: [
          'After the next setback, give yourself one evening to feel upset, then write one next step the following morning and do it.',
          'Write the setback in five lines: what happened, what was in your control and what was not.',
          'Tell one trusted person what happened and what kind of help you want, so you are not carrying it alone.',
        ],
      },
      {
        key: 'mindset',
        name: 'Belief that ability can grow',
        short: 'Seeing skills as something you can build',
        strong: 'You treat skills as things that improve with the right practice, and you learn from people who are ahead of you.',
        weak: 'You tend to see ability as fixed, compare yourself with others and avoid situations where you might look weak.',
        plan: [
          'Pick one skill you call weak and practise it for 20 minutes a day for two weeks, then compare week one with week two.',
          'Replace I am not good at this with I am not good at this yet, and add one practice step.',
          'Ask one person who is good at it how they began and what they got wrong at first.',
        ],
      },
      {
        key: 'effort',
        name: 'Staying with hard tasks',
        short: 'Continuing when work becomes slow or boring',
        strong: 'You keep going through dull or difficult stretches and break long goals into steps.',
        weak: 'You switch to easier things when a task gets hard, or stop when results do not show quickly.',
        plan: [
          'Do the hardest task first for a 25-minute timed block every day for two weeks.',
          'Decide a fair trial period before you start something new, and judge it only at the end.',
          'Break your current big goal into four weekly pieces and tick them off.',
        ],
      },
      {
        key: 'learn',
        name: 'Using feedback and mistakes',
        short: 'Turning errors and comments into improvement',
        strong: 'You look at your errors calmly, ask for feedback and change your method after a failure.',
        weak: 'You feel defensive about corrections, hide mistakes or repeat the same method after it has failed.',
        plan: [
          'Keep a mistakes page this fortnight: what happened, why, and one thing you will do differently.',
          'Ask one person more experienced than you for feedback on one finished piece of work.',
          'When you hear a correction, say thank you and repeat it back before you react.',
        ],
      },
      {
        key: 'drive',
        name: 'Purpose and motivation over time',
        short: 'Keeping a goal alive for months',
        strong: 'You know why your goal matters to you and keep working on it when nobody is watching.',
        weak: 'Your effort depends on praise or novelty, and you often switch goals when something new looks exciting.',
        plan: [
          'Write one sentence on why your goal matters to you personally, and put it where you study or work.',
          'Create a five-minute starter routine for low-energy days and use it at the same time daily.',
          'Choose a review date about eight weeks away before you allow yourself to change the goal.',
        ],
      },
    ],
    questions: CORE.map(({ d, text, reverse }) => (reverse ? { d, text, reverse } : { d, text })),
    readingTitle: 'How to read your resilience and growth mindset result',
    readingSections: [
      {
        title: 'These are habits, not a verdict on you',
        body: [
          'Each statement describes something you do, such as writing down what to change after a mistake or sticking with a task for a set time. That makes these areas trainable. A lower score means a habit you have not practised yet, not a fixed trait or a flaw.',
          'Resilience here does not mean coping alone or pushing through without rest. Telling a parent, teacher, senior or friend what is hard, and asking for help or feedback, is one of the habits this self-assessment looks for.',
        ],
      },
      {
        title: 'Why these five areas',
        body: [
          'Bouncing back, belief that ability can grow, staying with hard tasks, using feedback and keeping drive over time together describe how people handle low marks, backlogs, rejections, layoffs and plateaus. They are separate habits, so you can be strong in one and weak in another.',
          'If you are a student, setbacks and mindset may be the first areas to look at because marks and comparison are everywhere. If you are searching for a job or restarting after a break, effort and drive may matter more, because preparation needs time to show.',
        ],
      },
      {
        title: 'Compare areas with each other, not with other people',
        body: [
          'Your scores come only from your own answers, so there is no pass mark and no ranking. Look at which area is lowest and which is highest, then use the plan for the lowest one. Retake the self-assessment after a month and compare area by area.',
        ],
      },
      {
        title: 'Turn scores into examples',
        body: [
          'A score alone convinces nobody. Pick your strongest area and write two real examples of what you did after a setback or a correction. Concrete stories are easier for an interviewer or a mentor to understand than labels like resilient or hardworking.',
        ],
      },
    ],
    limits: [
      'This is a self-rating tool and shows how you describe yourself. It does not replace feedback from teachers, seniors or people who work with you.',
      'It is not a medical or mental-health assessment and cannot tell you whether you are coping well. If you feel unable to cope or have thoughts of harming yourself, please speak to a doctor, a counsellor or someone you trust. You can also call Tele-MANAS on 14416, a free national helpline.',
      'It is not an employer or admission test and does not predict selection, performance or exam results.',
      'Scores are not compared with other people, so there is no pass mark. Your result can change from week to week depending on what is happening in your life.',
    ],
    faqs: [
      {
        q: 'Is this resilience test free?',
        a: 'Yes. The self-assessment is free to take, and you get your area scores, advice for each answer you gave and a downloadable report without any payment.',
      },
      {
        q: 'Is this a growth mindset test?',
        a: 'One of the five areas, belief that ability can grow, covers how you think about skills, comparison and practice. The other four areas look at what you do after setbacks, on hard tasks, with feedback and over time, because a belief matters most when it shows up in habits.',
      },
      {
        q: 'Is this a grit test?',
        a: 'It covers the parts of grit people usually mean, staying with hard tasks and keeping a goal alive for months, as two of its five areas. It is a self-rating of your own habits with original statements, not a diagnosis or a label.',
      },
      {
        q: 'What is the difference between resilience and a growth mindset?',
        a: 'Resilience is how you respond after a setback, while a growth mindset is the belief that skills can improve with practice. They support each other: believing you can improve makes it easier to try again, and trying again after a setback gives that belief some evidence. This self-assessment scores both, along with effort, feedback and long-term drive.',
      },
      {
        q: 'Does being resilient mean handling everything on my own?',
        a: 'No. Asking a parent, teacher, senior, friend or counsellor for support is part of bouncing back, not a sign that you are weak. The setbacks area includes a statement about telling someone you trust, and the plans suggest who to talk to and what to ask.',
      },
      {
        q: 'How is the score worked out?',
        a: 'Statements are rated from 1 to 5, and the ones worded in the negative are reversed. In the situation questions, each option carries a score from 0 to 100. Each area score is the average of its statements and situations, shown out of 100, and the overall score is the average of the five areas.',
      },
      {
        q: 'What is a good score?',
        a: 'There is no pass mark. Scores are only against your own answers and are not compared with anyone else. A more useful question is which area is lowest for you today and what you will do about it in the next two weeks.',
      },
      {
        q: 'Can students and freshers use it?',
        a: 'Yes. The statements are about everyday habits after a bad result, a backlog, a rejection or a correction, so they apply to school students, college students, job seekers and working professionals. Your report adjusts the advice to the stage you choose.',
      },
      {
        q: 'Is this a mental health test?',
        a: 'No. It is a self-reflection tool about habits and is not a medical or mental-health assessment. If you feel unable to cope or have thoughts of harming yourself, speak to a doctor, a counsellor or someone you trust. You can call Tele-MANAS on 14416, a free national helpline.',
      },
    ],
    related: [
      {
        href: '/services/assessments/soft-skills-self-assessment/',
        title: 'Soft Skills Self-Assessment',
        description: 'Leadership, teamwork, adaptability, ownership and problem solving, scored separately.',
      },
      {
        href: '/services/assessments/communication-skills-assessment/',
        title: 'Communication Skills Assessment',
        description: 'Listening, speaking, writing, feedback and presenting, scored separately.',
      },
      {
        href: '/services/assessments/emotional-intelligence-test-careers/',
        title: 'Emotional Intelligence Test for Careers',
        description: 'Emotional skills that sit behind handling pressure, feedback and relationships at work.',
      },
      {
        href: '/services/assessments/confused-about-career-after-10th-test/',
        title: 'Confused About Career After 10th Test',
        description: 'Find out what is really holding up a decision after Class 10.',
      },
      {
        href: '/blog/career-change/rebuild-career-after-layoff-india/',
        title: 'Rebuild Your Career After a Layoff',
        description: 'Practical steps for restarting after a job loss.',
      },
      {
        href: '/blog/career-change/career-plateau-how-to-break-through-india/',
        title: 'Career Plateau: How to Break Through',
        description: 'What to do when growth at work has stalled.',
      },
      {
        href: '/blog/job-search/first-job-after-graduation-india/',
        title: 'First Job After Graduation',
        description: 'How to approach the first job search and the early months at work.',
      },
      {
        href: '/blog/skills/career-development-skills/',
        title: 'Career Development Skills',
        description: 'The skills that help careers grow, and how to build them.',
      },
    ],
    breadcrumbDescription: 'Free resilience and growth mindset self-assessment with five area scores.',
    webAppDescription:
      'A free original 40-question resilience and growth mindset self-assessment covering bouncing back from setbacks, belief that ability can grow, staying with hard tasks, using feedback and mistakes, and purpose and motivation over time, with five scores, an overall score, a practice plan and a downloadable report.',
    indexDescription: 'Free 40-question resilience and growth mindset self-assessment with five scores and a two-week plan.',
    indexNote: 'Five areas, about 7 minutes, free PDF report',
  },

  depth: {
    stageHeading: 'Which of these describes you best?',
    stageNote: 'Setbacks look different at each stage, from marks and comparison to rejections and layoffs, so your report adjusts the advice to match.',
    stages: [
      {
        key: 'school',
        label: 'School student',
        description: 'Class 8 to 12',
        title: 'Treat marks as feedback, not as a verdict on you',
        body: 'At school, bad marks and comparison with classmates are the main tests. The habit to build is looking at what the paper shows, and practising in small steps, while the results of others stay their own business.',
        actions: [
          'After each test, spend 20 minutes with the corrected paper and list where marks were lost: concept, careless error or time.',
          'Practise the weakest topic in three short sessions a week instead of one long panic before the exam.',
          'Compare your marks only with your own last test, and tell one adult if comparison at home or school is hurting your confidence.',
        ],
      },
      {
        key: 'college',
        label: 'College student',
        description: 'Degree, diploma or professional course',
        title: 'Handle backlogs and placement rejections with a plan',
        body: 'In college, a backlog, a poor semester or a placement rejection can feel final. A written recovery plan and a feedback habit turn each of them into the next move.',
        actions: [
          'List every backlog or weak paper with its exam date and give each a weekly study block until it is cleared.',
          'After each placement or internship rejection, note the round where you were stopped and ask a senior or the placement cell what that round tests.',
          'Join one project or club where you can try something new and fail in a low-stakes setting.',
        ],
      },
      {
        key: 'fresher',
        label: 'Fresher or job seeker',
        description: 'Looking for a first job or in the first years, facing rejections or probation',
        title: 'Keep applying while you improve what you send and say',
        body: 'First-job rejections, silent applications and probation reviews are discouraging because you have little track record yet. Treat each one as information about one stage of the process, and change one thing at a time.',
        actions: [
          'Keep a simple log of each application: date, stage reached, and one thing you will change next time.',
          'After every interview, write down the three questions you answered worst and practise them aloud the next day.',
          'If you are on probation, ask your manager for a short review every two weeks and note what to improve.',
        ],
      },
      {
        key: 'professional',
        label: 'Working professional',
        description: 'Experienced, changing careers, after a layoff or on a long plateau',
        title: 'Restart with small steps after a layoff, a break or a plateau',
        body: 'After a layoff, a long break or years on the same level, the hardest part is the story you tell yourself about being behind. Small daily steps, a short skill refresh and honest conversations rebuild momentum.',
        actions: [
          'Write down three things you did well in your last role, with the outcome, so your starting point is evidence and not fear.',
          'Spend 30 minutes a day on one current skill or tool relevant to the role you want, and keep a dated log.',
          'Speak to two people who restarted after a layoff, break or plateau and ask what the first month looked like.',
        ],
      },
    ],
    tips: CORE.map((c) => c.tip),
    tipsUp: [
      "Name your next step on paper by a set time, such as 9 pm the day after a bad result, and tick it off. Note how many hours passed before you started.",
      "Re-test your weak skill every Sunday with the same small task, such as one timed page, and write the time or score in one line. Four entries show whether practice is working.",
      "Raise the timer to 40 minutes on your two hardest tasks this week and log whether you stopped early. Note in one line what tempted you to stop.",
      "Review your mistakes page every Sunday for 10 minutes and circle any error that appears twice. For one repeating error, write a rule you will check before each attempt.",
      "Read your why sentence each morning for a week, then show it to one person and ask if it sounds like you. Add a real example if it feels vague.",
      "When doubt about the whole goal appears after a failure, write it down and wait 48 hours before deciding anything. Meanwhile ask one person on the same path about their own failures.",
      "When you catch the thought that some people are born good, write one skill you improved earlier and how many weeks it took. Keep that note as your answer to the thought.",
      "Mark the exact point where you usually switch, such as the first hour or the first hard question, and push 10 minutes past it. Tick on a calendar each day you did.",
      "When the defensive feeling rises, take three slow breaths and ask one question before replying. At week end, note which kinds of comments trigger it most.",
      "Send your three-line day list to a friend or study partner every Sunday. Also keep a dated tick sheet for the days you worked with nobody checking.",
      "Pick one item from your can change column and set a date and time to do it. Afterwards write whether it made a difference, and share the list with one person.",
      "Turn their answers into one change: choose a single method they described, try it daily for two weeks and report back to them on what happened.",
      "Add a Friday check where you count pieces done against the target and move any missed piece to the first slot next week. Keep four weeks of tick sheets.",
      "Ask the same person for feedback again after two weeks on a new piece, and show the one change you made. Keep both versions to see the difference.",
      "When you notice the replaying, set a 10-minute timer to write what you would do differently, then stop and start a task. Note how long the replaying lasted each day.",
      "Keep a weekly tally of the times you said yet, with the drill attached to each. On Sunday, do first any drill you skipped.",
      "On day three of any new effort, do that day's session anyway and add one measure to check at the end, such as pages done, a mock score or a speed.",
      "When you notice you are hiding something, tell the same trusted person within the day and add the check you now use to avoid it. Aim for one such mention a week.",
      "Tie the starter to a fixed trigger, such as right after tea or on reaching your desk, and tick each day on a calendar. After a week, stretch it to 15 minutes on low-energy days.",
      "Fix a weekly 15-minute check-in with the same person, such as Sunday evening, to share one hard thing and one good thing. Keep it even in an easy week.",
      "After your first low-risk attempt, repeat it in front of two or three people and ask one of them for a single comment. Note how you felt before and after.",
      "Write the start and end time of each focused session this week. Add one block with the phone out of sight, and extend your longest block by five minutes.",
      "Before you change the method, write a guess of why it failed. After two weeks compare the result with your guess, and keep a one-line note for each change.",
      "When a new idea tempts you, score it against your current goal on three questions written beforehand, such as time needed and what it gives you. Revisit the parked list on your review date.",
    ],
    strongTip: 'This habit already works for you. Write down one real example with the date and what you did, so you can use it in an interview, a college form or a talk with a mentor.',
    domains: {
      setbacks: {
        why: 'Everyone meets failure, rejection or loss at some point. What matters for your future is how you handle it: feeling it, learning from it, getting support when you need it and taking a next step. Doing this with other people, and not alone, is a strength.',
        roles: ['Exam preparation, placements, job search and any stretch with repeated rejections', 'Roles with targets, client pressure or frequent changes in plan', 'Long waits for outcomes, such as entrance results, interview decisions or a small business that is slow to start'],
        routine: [
          'Days 1 to 3: Write your last two setbacks in five lines each, noting what you controlled and what you did not.',
          'Days 4 to 7: After any disappointment, take one evening to feel it, then write and start one next step the next morning.',
          'Days 8 to 11: Tell one trusted person about a current worry and ask what they would do in your place.',
          'Days 12 to 14: Review what helped you recover and keep it as a short checklist for next time.',
        ],
        mistakes: ['Treating one result as a judgement on your whole ability', 'Going silent and carrying the setback alone for weeks, as if asking for help were a weakness', 'Waiting until you feel fully fine before taking any next step'],
        proof: ['A real story of a setback, what you did next and how long it took', 'A dated list of the next steps you took after a rejection or a poor result', 'A short recovery checklist you wrote and used more than once', 'A note of whom you asked for help during a hard time and what they suggested'],
        askOthers: 'When something went wrong for me, how did I behave afterwards, and did you feel I was open about needing help?',
        talkingPoints: ['You can describe a setback, the lesson and the next step plainly', 'You separate what you controlled from what you did not', 'You know when to ask for support and whom to ask, and can show how you restarted afterwards'],
        midStep: 'Keep a short recovery checklist, including one person you will tell, and use it the next time you are disappointed.',
      },
      mindset: {
        why: 'How you think about ability decides what you try. If you see skill as something that grows with practice, you are more likely to start things you are weak at and to learn from people ahead of you.',
        roles: ['Learning new subjects, exams that need repeated practice and career changes', 'Roles where tools, products or expectations keep changing', 'Roles that ask you to learn quickly, such as sales, customer support, data work and teaching'],
        routine: [
          'Days 1 to 3: List three skills you call weak and write what a small improvement in each would look like.',
          'Days 4 to 7: Practise one of them for 20 minutes a day and keep a dated note of what felt easier.',
          'Days 8 to 11: Ask one person who is good at it how they started and what they got wrong early on.',
          'Days 12 to 14: Compare your first and last practice notes, and choose the next skill to work on.',
        ],
        mistakes: ['Comparing your day one with someone else\'s year five', 'Avoiding new tasks so that nobody sees you being a beginner', 'Using the word never about a skill you have barely practised'],
        proof: ['A skill you improved over a few weeks, with dated practice notes', 'An example of learning from someone further ahead than you', 'A message or note from a teacher, senior or friend saying they saw you improve'],
        askOthers: 'Do I take on things I am not yet good at, or do I tend to avoid them?',
        talkingPoints: ['You treat skills as things you build with practice', 'You learn openly from people who are ahead of you', 'You start as a beginner without embarrassment and improve in public'],
        midStep: 'Choose one thing you avoid because you are not good at it yet, and do one visible attempt this month.',
      },
      effort: {
        why: 'Most worthwhile goals, an exam rank, a skill, a job search, have a long middle stretch that is slow and dull. Staying with it in planned blocks usually works better than relying on short bursts of high energy.',
        roles: ['Long exam preparation such as JEE, NEET, UPSC or banking exams', 'Job searches, skill courses and any project with a slow middle', 'Self-paced work such as freelancing, coding practice and online courses'],
        routine: [
          'Days 1 to 3: Cut your big goal into four weekly targets and write them down.',
          'Days 4 to 7: Do your hardest task first in a 25-minute timed block, phone in another room.',
          'Days 8 to 11: Raise the block to 35 minutes and add a short break before the next one.',
          'Days 12 to 14: Review which weekly target you met, and adjust only the next week.',
        ],
        mistakes: ['Judging a method after three days', 'Starting a new plan every time the old one gets boring', 'Counting hours instead of checking what the hours produced'],
        proof: ['A project, course or preparation you completed through a dull stretch', 'A weekly log showing steady practice over several weeks', 'A mock-test or practice score sheet showing results across many weeks'],
        askOthers: 'Do you see me finishing difficult things, or moving on when they get tough?',
        talkingPoints: ['You plan long goals in weekly pieces and keep going', 'You decide in advance how long to give a method before judging it', 'You keep going through the slow middle of long goals'],
        midStep: 'Pick one long task and give it the same time slot daily for two weeks, logging each session in one line.',
      },
      learn: {
        why: 'Mistakes and corrections tell you quickly what to change. People who use them openly usually find it easier to improve than people who defend or hide them, and the people around them can help sooner.',
        roles: ['Any role with reviews, appraisals, code or content checking, and client work', 'Exam preparation, where tests and mock papers show the gaps', 'Early career roles where managers and seniors give frequent corrections'],
        routine: [
          'Days 1 to 3: Start a mistakes page and write each error with the reason and one changed action.',
          'Days 4 to 7: Send one finished piece of work to a more experienced person with one specific question.',
          'Days 8 to 11: When corrected, say thank you and repeat the point back before replying.',
          'Days 12 to 14: Read your mistakes page, mark any pattern that repeats and change your method for it.',
        ],
        mistakes: ['Explaining why you were right before hearing the correction', 'Changing nothing after a failure and trying the same way again', 'Treating feedback as a comment on your worth instead of your work'],
        proof: ['A before and after example of work you improved after feedback', 'A mistakes page showing a method you changed', 'A message or review from a senior that mentions your improvement'],
        askOthers: 'What is one thing in my work you would change, and how did you feel I reacted when you told me?',
        talkingPoints: ['You ask for feedback and show what you changed', 'You can talk about a mistake openly and say what you learned', 'You turn corrections into visible changes in your work'],
        midStep: 'Ask for feedback on one piece of work every two weeks and change one thing each time.',
      },
      drive: {
        why: 'Strong results over months come from knowing why a goal matters to you and having a way to start on low-energy days. Without it, effort rises and falls with praise, novelty and mood.',
        roles: ['Self-driven work such as freelancing, studying for competitive exams and building skills alone', 'Long career transitions where nobody is checking your progress', 'Leadership, entrepreneurship and any path with few outside checkpoints'],
        routine: [
          'Days 1 to 3: Write one sentence on why your goal matters to you personally and keep it visible.',
          'Days 4 to 7: Set a five-minute starter routine for low-energy days and use it at the same time daily.',
          'Days 8 to 11: Write your own end-of-day check of three lines on what you finished.',
          'Days 12 to 14: Choose a review date about eight weeks away and decide what you will look at then.',
        ],
        mistakes: ['Switching goals whenever a new idea looks more exciting', 'Working only when someone is watching or praising', 'Choosing goals only because family or friends chose them'],
        proof: ['A goal you worked on for several months with dated milestones', 'A routine you built that kept you going without outside checking', 'A written reason for your goal, dated, that you reviewed at least twice'],
        askOthers: 'What do you think I really want from this goal, and does my effort match it?',
        talkingPoints: ['You can say why your goal matters to you in one sentence', 'You keep a routine that works on low-energy days', 'You know your reasons and can show months of steady work'],
        midStep: 'Keep a parked ideas list and only switch goals at a planned review date.',
      },
    },
    thirtyDay: [
      'Week 1: Do the first half of the routine for your lowest area and write one line each day on what you tried.',
      'Week 2: Finish the routine and ask two people for feedback on how you handle that area.',
      'Week 3: Move to your second-lowest area and use two steps from its plan.',
      'Week 4: Retake the self-assessment, compare each area score and write two real examples for your strongest area.',
    ],
  },

  extras: [
    { ...x(['school'], 'setbacks', 'After a low mark, I can still sit down and study the next subject on the same day.', 'Keep a fixed study time that does not change after a bad result. Open the next subject for just 20 minutes and let the habit pull you back in.'), up: "Pair it with a fixed time, such as 6 pm daily, so the next subject starts without any deciding. Tick each day on a wall calendar for two weeks." },
    { ...x(['school'], 'mindset', 'When classmates score more than me, I feel I should stop trying in that subject.', 'Write your own last three marks in the subject and look only at the direction. Then pick one topic where a small gain is possible this week and practise it.', true), up: "When the thought to stop appears, finish one practice question first and note it. Then compare your own last three marks and show any gain to a teacher." },
    { ...x(['school'], 'effort', 'I keep practising a topic I find difficult, such as maths or a language, in short sessions instead of skipping it.', 'Fix three 20-minute sessions a week for your hardest topic and solve or write something every time. Short, regular sessions are easier to keep up than one long session the night before the test.'), up: "Note how many problems or lines you finish in each session and try to beat it by one next time. Ask your teacher to check one piece of that work every week." },
    { ...x(['school'], 'learn', 'I look through my corrected answer sheet to see exactly where I lost marks.', 'Make three columns for each corrected paper: did not know, knew but made an error, ran out of time. Practise the biggest column first.'), up: "Rewrite one lost-mark answer correctly each week and ask your teacher to check it. Keep the rewrites in one file to read before the next paper." },
    { ...x(['school'], 'drive', 'I can say in one sentence why I am studying a subject that is not only about marks.', 'Write the sentence for one subject, such as I want maths because I like solving puzzles or because my chosen course needs it. If you cannot, ask a teacher or an older student how the subject is used after school.'), up: "Add one real use of the subject, found by asking an adult who works with it, to your sentence. Read it before your first study session each week." },
    { ...x(['college'], 'setbacks', 'When I get a backlog, I make a plan with dates for clearing it instead of avoiding it.', 'List every backlog paper with its next exam date, count the weeks and fix a weekly study block for each. A plan on paper reduces the fear of the pile.'), up: "Check the plan every Sunday against the dates and mark each block done or missed. Show it to a friend or senior once a fortnight so someone else sees it." },
    { ...x(['college'], 'mindset', 'When classmates get placed before me, I feel it proves I am less capable.', 'Compare your own preparation this month with last month: aptitude practice, projects, mock interviews. Placement order depends on many things, so judge your progress on the part you control.', true), up: "When the thought appears, list what you did this week for placements and book one mock interview with a senior. Judge progress by the mock feedback." },
    { ...x(['college'], 'learn', 'After a poor viva, project review or interview, I ask faculty or seniors what I should improve.', 'Within two days of a poor review, send the faculty member or a senior one question: what is the one thing I should change before next time. Write the reply down.'), up: "Keep the replies in one notebook and look for a comment that repeats. Act on that one in your next review and tell the person who gave it what you changed." },
    { ...x(['college'], 'effort', 'I keep preparing for placements or higher studies in weeks when there is no test or deadline.', 'Put two fixed slots in your weekly timetable, such as Saturday morning and Wednesday evening, each with one output like two aptitude sets or one coding problem. Check on Sunday whether the outputs exist.'), up: "Keep the two slots on the same days each week and log the output in one line each. After four weeks, count how many were done and raise one output slightly." },
    { ...x(['college'], 'drive', 'I can say why I chose my course, even when marks or placement talk make me doubt it.', 'Write three reasons for your course that have nothing to do with other people. If you cannot, speak to a senior working in a related field about what the work looks like.'), up: "Copy your reasons onto the first page of your planner and read them at the start of each month. Ask a senior whether your daily work matches them." },
    { ...x(['fresher'], 'setbacks', 'After a rejection, I note which stage stopped me and what I will change before the next application.', 'Keep a log with the stage reached, such as resume, test, interview or HR round, and change one item before the next application. Patterns usually become clear after several entries.'), up: "After every ten entries, read the log for a repeating stage and fix that stage first. Share the log once with a senior or friend for another view." },
    { ...x(['fresher'], 'learn', 'After an interview, I write down the questions I answered poorly and practise them aloud.', 'Within an hour of the interview, write the three weakest answers and rehearse better versions aloud the next day. Repeat for every interview.'), up: "Record yourself answering one weak question and listen once for filler words or missing examples. Ask a friend to score the redone answer on one point you choose." },
    { ...x(['fresher'], 'effort', 'I keep applying and preparing on days when no replies arrive.', 'Set a small daily quota, such as five applications or one hour of interview practice, and track it. Judge yourself on the quota you control, not on replies.'), up: "Attach a time to the quota, such as applications sent before 11 am, and track it in a sheet. At week end find your weakest day and move that day's quota earlier." },
    { ...x(['fresher'], 'mindset', 'When a job post asks for a skill I lack, I plan how to learn it instead of dropping the post.', 'Take one post you like and mark each requirement as have, can learn in a month, or far away. Start a free course or small project for the first can-learn skill and apply if the remaining gaps are small.'), up: "Build a small dated project for the can-learn skill and ask someone in that field to look at it. Apply once you can show it, even if one gap remains." },
    { ...x(['fresher'], 'drive', 'During probation or my first months at work, I can name the skill I want to be better at in six months.', 'Choose one skill your manager mentions most often, write a six-month target for it, and share it with your manager so feedback comes against a clear goal.'), up: "Note one example each week of using that skill and review the notes with your manager monthly. Keep them ready for your first appraisal conversation." },
    { ...x(['professional'], 'setbacks', 'After a layoff, a bad appraisal or a missed promotion, I can separate what happened to me from what it says about my ability.', 'Write the event in three plain facts and then, separately, three examples of work you did well. Reading both lists stops one event from becoming your whole story.'), up: "Show both lists to one trusted colleague and ask if anything is missing. Then use one item from the achievements list in your next conversation or application." },
    { ...x(['professional'], 'mindset', 'I feel too old or too late to learn a new tool or start in a new field.', 'Find two people who started a similar move at your age or later and ask how long the first year took. Then set a four-week learning target in the new tool.', true), up: "When the thought appears, still log 30 minutes on the new tool that day. After two weeks, show a small output to a colleague and ask for one comment." },
    { ...x(['professional'], 'drive', 'I can describe what I want from the next few years of work, not only what I want to leave behind.', 'Write the next role you want in two lines and three things you would need to learn or show. A direction towards something is easier to sustain than an escape from something.'), up: "Check your two-line target each month against what you actually did and change one activity to fit. Share it with a mentor and ask if the next step is realistic." },
    { ...x(['professional'], 'learn', 'I find it hard to accept feedback from someone younger or more junior than me.', 'Next time, listen to the full point, write it down and ask one question about it. Try the suggestion once for two weeks before deciding whether it is useful. Who gave it matters less than whether it works.', true), up: "Keep a dated note of each suggestion from a junior colleague, what you tried and what happened. Review the notes after a month to see if the source mattered." },
    { ...x(['professional'], 'effort', 'After a long break or plateau, I restart with a small daily routine instead of waiting to feel ready.', 'Begin with 30 minutes a day at a fixed time, such as before work or after dinner, and log each day. Increase only after two steady weeks.'), up: "Fix a trigger, such as after dinner tea, and keep a streak calendar. After two steady weeks, add one small output, such as a one-page summary, each Friday." },
  ],

  stageAdvice: {
    school: {
      setbacks: sa('At school, a bad mark in front of family and classmates can feel bigger than it is.', 'After a low mark, sit with the corrected paper for 20 minutes and write the three biggest lost-mark reasons.', 'Tell a parent, teacher or older sibling how you feel about the result, and say what would help, so you are not handling it alone.'),
      mindset: sa('At school, comparison with toppers and friends shapes how you see your own ability.', 'Track only your own marks in a subject over three tests and look at the direction, not the rank.', 'Ask a classmate who improved in a subject what they changed in the last term.'),
      effort: sa('At school, the hard part is staying with a difficult subject when the syllabus is long.', 'Break a chapter into daily targets of two pages or five problems and tick them off.', 'Study the hardest subject first for 30 minutes, before your favourite one.'),
      learn: sa('At school, the corrected answer sheet and the teacher\'s remarks are your best feedback.', 'Rewrite two wrong answers properly in your notebook after each test.', 'Ask your teacher one question after each test: what is the one thing that would have earned me more marks.'),
      drive: sa('At school, motivation is easily tied to marks, tuition and what family expects.', 'Write one reason you want to study a subject that has nothing to do with marks.', 'Fix a daily study start time and place so you start even on tired days.'),
    },
    college: {
      setbacks: sa('In college, backlogs, a poor semester or placement rejections can make you feel left behind.', 'Make a dated clearing plan for each backlog and review it every Sunday.', 'After a rejection, note the stage and ask the placement cell or a senior what that round looks for.'),
      mindset: sa('In college, placement news and social media make comparison constant.', 'Mute comparison for a week and track three things you improved, such as aptitude practice, a project and mock interviews.', 'Join a skill group where everyone is a beginner in something and practise in front of them.'),
      effort: sa('In college, long gaps between deadlines make steady effort hard.', 'Set weekly targets for placement preparation, such as two aptitude sets and one coding or case problem.', 'Use a fixed library or study slot daily, with the phone away, for the dull parts of the syllabus.'),
      learn: sa('In college, viva, project reviews and mock interviews give feedback if you ask for it.', 'After each review, write down the three comments you heard and the change you will make.', 'Ask a senior to do a mock interview and note every question you hesitated on.'),
      drive: sa('In college, it is easy to drift between course, placement preparation and other interests.', 'Write why you chose your course and what work you hope to do, and check it at the start of each semester.', 'Choose one project or skill to stay with for a full semester, not a month.'),
    },
    fresher: {
      setbacks: sa('As a fresher, repeated rejections or silence after applications can wear down your confidence.', 'Log each application with the stage reached, and change one thing before the next ten.', 'Keep one fixed daily activity, such as a walk or practice session, so rejections do not control your whole day.'),
      mindset: sa('As a fresher, you are comparing your start with people who already have experience.', 'Write the three skills your target role asks for and mark where you are today and where you want to be in eight weeks.', 'Ask a recent joiner in a company you like how they got in and what they could not do in the first month.'),
      effort: sa('As a fresher, the job search is long and replies are slow.', 'Set a daily quota of applications and one hour of skill or interview practice, and track the quota.', 'Review your log every Sunday and decide only one change for the next week.'),
      learn: sa('As a fresher, probation reviews and interview outcomes carry feedback you must go and collect.', 'Ask your manager for a short review every two weeks during probation and write down each point.', 'After rejections, ask recruiters politely for one line of feedback, and accept silence calmly.'),
      drive: sa('As a fresher, the pull of any job can push you to forget what you actually want from your first role.', 'Write which two skills you want from your first job, and check offers against them.', 'Once you join, set a six-month learning goal and share it with your manager.'),
    },
    professional: {
      setbacks: sa('As a professional, a layoff, missed promotion or restart after a break can shake your sense of who you are at work.', 'List three facts about what happened and three achievements from your last role to keep them separate.', 'Talk to two people who restarted after a layoff or a break and ask what the first month was like.'),
      mindset: sa('As a professional, the belief that you are too old, too late or too specialised can stop you from trying.', 'Spend 30 minutes a day on one new tool in your target field for four weeks and share the result with a peer.', 'Replace I cannot learn this at my stage with a specific question about the first step and answer it.'),
      effort: sa('As a professional, long plateaus and busy schedules make steady learning hard.', 'Block a fixed 30-minute learning slot at the same time every day and protect it.', 'Choose one visible outcome in eight weeks, such as a small project or a certificate, and work backwards.'),
      learn: sa('As a professional, honest feedback is rare, so you have to ask for it.', 'Ask your manager and one peer what single change would help you most in the next year.', 'After an appraisal or an interview, write the feedback in your own words and one action you will take.'),
      drive: sa('As a professional, motivation can fade when the work no longer stretches you.', 'Write what you want from the next three years and the one skill that gets you there.', 'Choose a side project or course that connects to that direction and set a milestone date.'),
    },
  },

  scenarios: [
    sc('setbacks', 'You failed a test or exam you had prepared for. The result is public. What do you do over the next two days?', [
      o('Take the evening off, then go through the paper, list where marks were lost and make a revision plan', 100, 'Giving the feeling its time and then turning to the paper is how most people recover. Keep the list of lost marks and use it to decide your next three study sessions.'),
      o('Ask a friend who scored well to sit with you for an hour, go through the paper question by question, and copy their way of revising for the next test', 67, 'Learning from a friend is sensible, but copying their method before you know your own gaps can miss the point. First list where you lost marks, then ask them only about those topics.'),
      o('Study two hours more every day for a week with the same notes and the same method', 33, 'The effort shows commitment, yet the same method tends to give a similar result. Spend 20 minutes with the corrected paper first and change one thing in how you prepare.'),
      o('Put the paper away for now, since seeing the marks again will only hurt, and start fresh with the next chapter', 0, 'Looking away protects your mood for a few days but leaves the cause in place, and the same gaps can cost marks again. If opening the paper alone feels hard, go through it with a teacher or a friend and mark every question where you lost marks.'),
    ]),
    sc('setbacks', 'You applied for a job or a seat in a course and were rejected without a reason. What do you do?', [
      o('Note the stage where you were stopped, change one thing about it and send the next application this week', 100, 'Treating a rejection as information about one stage keeps you moving and shows you what to test. Log the stage and the change for your next ten applications and look for a repeating pattern.'),
      o('Write to the recruiter or the college asking for feedback, and hold back new applications until you hear from them, even if it takes a week or more', 50, 'Asking for feedback is a good move, but many places never reply and the pause costs you time. Send the request, then keep applying while you wait.'),
      o('Apply to twenty more places in the next two days using the same resume, since more attempts should bring one yes', 33, 'Speed helps only when something changes between attempts. Read your first few rejections for one common stage, fix that, and then send the next batch.'),
      o('Take a month off, since the process feels unfair and nothing you do seems to matter', 17, 'Feeling that the process is unfair is natural, and a short rest is fine. Limit the break to a few days and then send one improved application to restart the habit.'),
    ]),
    sc('mindset', 'A classmate or colleague picks up a skill you struggle with in half the time. What do you think and do?', [
      o('Put it down to talent: some people pick this up fast and others do not, so you leave it to them', 0, 'This view ends practice before it begins, and a skill that looks like a gift often has hours of practice behind it. Ask the person how they started and pick one small drill to try this week.'),
      o('Ask how they practise and what they got wrong early on, then try one of their methods for two weeks', 100, 'Their speed is information about method, not a limit on you. Write down what they tell you and test one part of it daily for two weeks, noting any change.'),
      o('Work extra every evening for a month on the skill alone, and set yourself a small test at the end to see how far you have come', 67, 'Extra practice and a self-test show real drive. Add one conversation with the person who learned fast, so your hours go into a better method and not only more repetition.'),
      o('Stay away from that skill for now and spend your time on things you already do well, so your confidence stays up', 33, 'Building on strengths is useful, but avoiding the weak skill leaves the gap open. Give the skill two short sessions a week while you keep using your strengths.'),
    ]),
    sc('mindset', 'You are asked to try something you have never done, and you may look clumsy in front of others. What do you do?', [
      o('Say you are busy this time and let someone else take it', 0, 'Stepping aside saves you from embarrassment today and from learning tomorrow. Offer to do one small piece next time, and tell the group it is your first attempt.'),
      o('Practise at home for a week with videos or notes, and join in only once you can do it without mistakes, so you do not waste anyone\'s time', 67, 'Preparing is useful, but waiting for a mistake-free start means you may never join. Fix a date to take part and use the week at home to reach that date, not perfection.'),
      o('Say you are new at it, try a small part and ask for one tip afterwards', 100, 'Saying you are new lowers the pressure, and a tip turns a clumsy attempt into learning. Ask the same person again next time so that progress becomes visible to both of you.'),
      o('Join in and act confident, and do not ask any questions so that nobody sees you are unsure', 33, 'Confidence helps you start, but hiding doubt lets small errors grow unseen. Ask one question in the first ten minutes and see how people respond.'),
    ]),
    sc('effort', 'Three weeks into a course or exam preparation, the topic has become dull and hard. What do you do?', [
      o('Move to a newer course that looks easier and more exciting', 0, 'A new course feels like progress, yet the hard middle will arrive there too. Set a fair trial period for the current one and judge it only when that period ends.'),
      o('Keep going exactly the same way, because every serious course has a boring stretch', 67, 'Accepting that the middle is dull is realistic. Pushing on without changing anything can wear you down though, so add daily targets and one change of format, such as practice questions in place of reading.'),
      o('Take a full week off to refresh yourself and restart when you feel interested again, since forcing yourself has not worked before', 33, 'Rest has a place, but waiting for interest often turns one week into three. Restart with a five-minute daily start and let the interest follow the action.'),
      o('Swap some reading for timed practice questions for two weeks, then judge the course', 100, 'A change of format often makes a dull stretch easier to carry, and the two-week limit stops you from quitting on a bad day or drifting. Put the judging date in your calendar today and add daily targets.'),
    ]),
    sc('effort', 'You have been stuck on the same hard topic for two weeks and your own revision is not helping. What do you do?', [
      o('Keep repeating the same chapter alone for another two weeks, because asking for help feels like admitting you are weak', 33, 'Persistence is useful, but repeating a method that is not working rarely fixes the gap. Asking is a normal study step, so write down the exact point where you get stuck and ask someone by the weekend.'),
      o('Write down three lines on where exactly you get stuck, with two questions you tried, and ask a teacher or senior for 15 minutes', 100, 'Asking with specifics makes it easy for someone to help and shows you have already tried. Book the time this week and note the one explanation that finally made sense.'),
      o('Leave the topic for now and come back to it close to the exam', 17, 'Leaving it can give a rest, but hard topics usually need several rounds. Set a date within the next week to return with a fresh method or a helper.'),
      o('Watch a few online lectures on it every evening to get a new explanation', 67, 'A different explanation can unlock a topic, and this is a good step. Watching is passive though, so solve two problems after each lecture and take the ones you cannot solve to a teacher.'),
    ]),
    sc('learn', 'Your senior or teacher returns your work with many corrections. What do you do?', [
      o('Explain the reason behind each point so they know you tried, and then make the changes', 33, 'Explaining feels natural, but it can sound defensive and use up their patience. Listen to the full list first, say thank you and ask only one clarifying question.'),
      o('Redo the whole piece from scratch on your own so the next version has no corrections at all', 17, 'Wanting a clean version shows pride in your work, yet it delays feedback and hides the real pattern. Fix the points marked, then show a smaller part early to check you are on track.'),
      o('Fix every correction, group them into patterns and ask your senior about the two that repeat most', 100, 'Fixing everything shows you take the advice seriously, and asking about the repeating points helps you avoid the same mistakes. Send the next piece within a week and mention what you changed.'),
      o('Fix every correction the same day exactly as marked and send it back, without asking why each was needed', 67, 'Quick, complete fixing shows discipline. Without knowing why, the same mistakes can return, so ask the reason behind the two most repeated corrections.'),
    ]),
    sc('learn', 'You made a mistake in your work that nobody has noticed yet. What do you do?', [
      o('Fix it quietly yourself and say nothing, since the final work is now correct', 0, 'A quiet fix feels tidy, but the cause stays hidden and someone else may repeat the mistake or discover it later. Tell the person who owns the work in two sentences today, and note what caused it.'),
      o('Tell the person affected today what happened, how you are fixing it and what you will do so it does not repeat', 100, 'Telling early lets others protect themselves and builds trust in you. Add a one-line note of the cause to your mistakes page so the same slip is easier to spot next time.'),
      o('Correct it yourself right now and mention it in your next regular update, once the fix is ready to show', 67, 'Fixing first is a sensible instinct, but if someone depends on the work, the next update may be too late. Send a short message now and attach the fix when it is ready.'),
      o('Watch for a few days to see whether it causes any problem for anyone before saying a word', 33, 'Waiting can feel practical, yet a problem found by someone else looks worse than one you reported yourself. Give yourself today as the limit for raising it.'),
    ]),
    sc('drive', 'Two months into a long goal, your enthusiasm has faded. What do you do?', [
      o('Start looking for a new goal that excites you more, because this one has stopped doing that', 17, 'A new goal gives a burst of energy, and the same dip tends to arrive there too. Check whether your reason still holds before you leave, and write down what you would be giving up.'),
      o('Keep the goal, shrink the daily task to five minutes for a week and fix a date to review it', 100, 'A tiny task lowers the barrier on flat days, and the review date turns a mood into a decision. Choose that date today, about two or three weeks away, and re-read your own reason for the goal then.'),
      o('Ask two friends to check on your progress every week and share your daily target with them in a chat group', 67, 'Support from friends is a real help, and sharing a target makes it harder to drift. Add your own end-of-day check of three lines too, so the habit continues in weeks when they forget to ask.'),
      o('Carry on as before and ignore how you feel, since feelings change', 33, 'Persistence matters, but ignoring a long dip can drain your interest further. Lighten the routine, name what has changed and, if it feels heavy, tell someone you trust before pushing on.'),
    ]),
    sc('drive', 'You are halfway through your plan when a friend shows you a new course or business idea that looks exciting. What do you do?', [
      o('Switch now, since the new idea clearly looks better than what you are doing', 0, 'New ideas look better because you have not yet met their hard parts. Note the idea down and give it a fair look at your planned review date.'),
      o('Spend one evening finding out what the new idea really involves and talk to someone who has done it before deciding', 67, 'One evening of homework is a fair price for curiosity. Keep your current plan running while you do it, and decide only at the review date so that you are not reacting to excitement.'),
      o('Give half of each week to each, so you do not lose either', 33, 'Splitting looks fair but often leaves both half done. Finish the current review point first and then decide.'),
      o('Put the idea on a parked list, finish your current review point, then compare both on the same questions', 100, 'Parking the idea protects your goal, and judging both on fixed questions makes any switch a decision and not a reaction. Write the questions now, for example time needed, cost and who does this work.'),
    ]),
    { ...sc('setbacks', 'A friend scores far more than you in a school unit test and everyone is talking about it. You scored low. What do you do?', [
      o('Tell yourself you are not a studies person and put more time into what you are good at', 0, 'One test cannot decide your ability. Your strengths deserve time, but give this subject a fair trial of three or four weeks with a changed method.'),
      o('Avoid talking about marks with that friend for a while, since it makes you feel bad', 33, 'Taking space is fine for a day or two. After that, a short chat about how they revise is likely to help you more than distance.'),
      o('Compare with your last test, check where marks went, ask your friend how they revise and try one change', 100, 'Measuring against your past self, reading the paper and borrowing one method turn an uncomfortable moment into a plan. Choose the single change for the next test and write it on the first page of your notebook.'),
      o('Ask your teacher to explain the topics you lost marks on, and add an hour of study every evening this week', 67, 'Going to the teacher is a very good step. For the extra hour, use practice questions on those topics and not only reading, and tell the teacher what you tried so the help can be specific.'),
    ]), stages: ['school'] },
    { ...sc('setbacks', 'You have a backlog in one paper and your next semester begins soon. What do you do?', [
      o('Focus on placement preparation now and take the backlog exam whenever the next chance comes', 17, 'Placements matter, yet some companies ask for no pending backlogs, so a pending paper can block you later. Check your college rules and the next exam date, and give the backlog a weekly slot alongside.'),
      o('Note the exam date and syllabus, split it into weekly blocks and ask a senior who cleared it for notes and method', 100, 'A dated plan and a senior\'s method turn the backlog into a defined task. Show the plan to the senior and ask whether the weekly blocks look realistic.'),
      o('Apply for re-evaluation if your university allows it, and plan for the repeat exam only after the result comes', 33, 'Re-evaluation can be worth trying where the university allows it, so check the official notice for dates. Do not pause preparation while you wait, because the result may not change and the exam date will not move.'),
      o('Study only the last three years\' question papers just before the exam and keep your main attention on the new semester', 50, 'Past papers are useful, but a short burst before the exam leaves little room if the syllabus has changed. Start using them in weekly blocks from now to see what is asked.'),
    ]), stages: ['college'] },
    { ...sc('setbacks', 'You have faced several rejections after interviews for your first job. What do you do?', [
      o('Decide this kind of job is not for you and stop applying in this field', 0, 'A run of rejections hurts, yet it does not decide your fit for a field. Take a few days to rest, then check at which stage you were stopped most often.'),
      o('Look at the job posts that rejected you and spend two weeks learning the tool or skill most of them list before applying again', 67, 'Reading what posts ask for is smart. A two-week pause in applications is long, so learn the skill while still sending a few applications each week.'),
      o('Ask a friend for a mock interview, practise your three weakest answers and keep applying with a daily quota', 100, 'A mock interview shows what an interviewer sees, and the daily quota keeps you moving while you improve. Note your three weakest answers and say better versions aloud the next day.'),
      o('Rest for a couple of weeks until the hiring season looks better, then start again', 33, 'Rest helps for a few days, but a long gap makes restarting harder. Keep a light routine of one application or one practice answer each day.'),
    ]), stages: ['fresher'] },
    { ...sc('setbacks', 'You were laid off, or are restarting after a long break, and feel behind your peers. What do you do?', [
      o('Wait until you feel ready before updating your resume or contacting anyone, so people see you at your best', 17, 'Taking time to recover is fine, but readiness often grows from small actions. Update the resume this week and message one person you have worked with.'),
      o('Apply to every opening you can find this month, fit or not, because any job restarts your income and confidence', 67, 'Needing income is real, and applying widely can help. Choose one or two target roles as well and shape your resume for them, so scattered applications do not tire you out.'),
      o('Compare yourself with former colleagues and think about changing to a completely different field', 33, 'Comparison can cloud judgement. Decide on a direction after talking to two people who work in that field, not out of fear of being behind.'),
      o('Write down what you achieved in your last role tonight, then use it to ask two former colleagues for advice and leads', 100, 'A list of achievements gives you facts to work from, and asking colleagues brings in people who know your work. Add a 30-minute daily learning slot once you hear what roles they suggest.'),
    ]), stages: ['professional'] },
  ],

  phrases: {
    setbacks: [
      `"That did not go the way I wanted. What is one thing I can change for next time?"`,
      `"I am upset about it, and I will take until tomorrow morning to feel that, then I will start the next step."`,
      `"It did not work this time, and I am still going to try again with a changed approach."`,
    ],
    mindset: [
      `"I am not good at this yet, and I will practise it for 20 minutes a day."`,
      `"How did you start, and what did you get wrong in the beginning?"`,
      `"I am new to this, so please tell me one thing I could improve."`,
    ],
    effort: [
      `"I will work on this for 25 minutes before I decide whether to stop."`,
      `"This week's target is ... and I will tick it off by Sunday."`,
      `"I will give this method three weeks before I judge it."`,
    ],
    learn: [
      `"Thank you. Could you show me one example so I can fix it?"`,
      `"I made a mistake in ... and here is what I have changed."`,
      `"What is the one change that would improve this the most?"`,
    ],
    drive: [
      `"I want to do this because ..."`,
      `"I will review this goal on ... and decide then whether to continue."`,
      `"On low-energy days, I will do the five-minute starter and see how I feel."`,
    ],
  },

  stagePlan: {
    school: [
      'After each test, spend 20 minutes with the corrected paper and list where marks were lost.',
      'Practise your hardest topic in three short sessions each week.',
      'Compare your marks only with your own last test, not with classmates.',
      'Tell a parent, teacher or counsellor when comparison or results are weighing on you.',
    ],
    college: [
      'List every backlog or weak paper and give each a dated weekly study block.',
      'After each rejection, note the stage and ask a senior what that round tests.',
      'Set weekly targets for placement preparation and tick them off every Sunday.',
      'Take on one project or club task where you can try something new and learn from a failure.',
    ],
    fresher: [
      'Log each application with the stage reached and change one thing before the next ten.',
      'After every interview, write your three weakest answers and practise them aloud.',
      'Set a daily quota of applications and one hour of skill practice.',
      'During probation, ask for a short review every two weeks and act on one point each time.',
    ],
    professional: [
      'Write three achievements from your last role to anchor your story in evidence.',
      'Fix a 30-minute daily learning slot for one skill relevant to your next role.',
      'Speak to two people who restarted after a layoff, break or plateau.',
      'Set an eight-week outcome, such as a small project or certificate, and work back from it.',
    ],
  },

  talk: {
    setbacks: {
      q: 'Tell me about a time you failed or were rejected. What did you do next?',
      a: 'Pick one real setback, say plainly what happened and what part you controlled, then describe the next step you took and how long it took. End with what you do differently now.',
      line: 'Recovered from [setback] by [specific action], and applied the lesson to [later result].',
    },
    mindset: {
      q: 'Tell me about a skill you were weak at and how you improved it.',
      a: 'Name the skill, how you practised (frequency and method), who you learned from and what changed after a few weeks. Show that you began as a beginner.',
      line: 'Improved [skill] from [starting point] to [result] over [time] through [practice method].',
    },
    effort: {
      q: 'Tell me about a long or difficult task you stayed with when it got dull.',
      a: 'Describe the goal, how you broke it into weekly steps, what you did when motivation dipped and the final result. Mention the routine you used.',
      line: 'Completed [long task or course] over [time] by working in [weekly or daily blocks], delivering [result].',
    },
    learn: {
      q: 'Tell me about feedback you received that was hard to hear. What did you change?',
      a: 'Describe the feedback without blaming anyone, how you checked you understood it, what you changed and what improved. Avoid presenting it as a trick answer such as being too much of a perfectionist.',
      line: 'Acted on feedback about [issue] by [change], which improved [result].',
    },
    drive: {
      q: 'Why do you want this role or goal, and what keeps you going when it is hard?',
      a: 'Give your own reason in one sentence, one example of working on it over months and the routine that keeps you going. Mention a step you took without being asked.',
      line: 'Worked on [goal] for [months] through [routine], reaching [milestone].',
    },
  },

  talkTitles: {
    strong: 'How to show this strength in an interview or on your CV',
    weak: 'How to answer if you are asked about your weakest area',
    intro: 'Interviewers ask how you handle setbacks and feedback through real stories. Prepare one example for each area, with what happened, what you did and what changed.',
    mode: 'interview',
  },
};
