// Maps each BOFU page slug (relative to /services/career-counselling-and-career-guidance/, no trailing slash) to its image file id.
// Files live at public/images/bofu/<id>.webp. See docs/BOFU_IMAGE_PLAN.md for prompts, sizes, and which pages share each image.
// A new page picks its image id from the group it belongs to; add one line here. Pages whose file does not exist yet render no image.
export const BOFU_IMAGE_ALT: Record<string, string> = {
  "hero-school-students-parents": "A Class 10 student and a parent comparing stream options at a desk",
  "hero-class-11-12": "A Class 11-12 student choosing between Science, Commerce and Arts paths",
  "hero-stream-specific": "Four study streams shown side by side: biology, maths, commerce and arts",
  "hero-graduates-college": "A graduate with a laptop planning a skill roadmap after college",
  "hero-working-professionals": "A working professional weighing a career move at a desk",
  "hero-online-session": "A one-on-one online career counselling session on video",
  "hero-pricing": "Simple plan cards and a notebook showing career counselling pricing",
  "hero-evaluation": "A four-point checklist beside a laptop for judging a career guidance provider",
  "hero-assessment": "A student taking an online career assessment on a tablet",
  "hero-hub": "The career counselling and guidance service shown as a path from confusion to a next step",
  "hero-career-counselling": "A career counsellor and a client reviewing a decision together",
  "hero-career-guidance": "A guidance roadmap from options to a skill-first plan",
  "hero-helpline-whatsapp": "A WhatsApp chat with a career counsellor on a phone",
  "hero-locations-hub": "A map of India with city pins linked to one online service",
  "city-delhi": "Delhi skyline illustration for career counselling in Delhi and nearby areas",
  "city-mumbai": "Mumbai skyline illustration for career counselling in Mumbai and nearby areas",
  "city-bangalore": "Bangalore skyline illustration for career counselling in Bangalore",
  "city-hyderabad": "Hyderabad skyline illustration for career counselling in Hyderabad",
  "city-chennai": "Chennai skyline illustration for career counselling in Chennai",
  "city-kolkata": "Kolkata skyline illustration for career counselling in Kolkata",
  "city-pune": "Pune skyline illustration for career counselling in Pune",
  "city-ahmedabad": "Ahmedabad skyline illustration for career counselling in Ahmedabad",
  "region-north": "Northern India regional skyline illustration",
  "region-west": "Western India regional skyline illustration",
  "region-south": "Southern India regional skyline illustration",
  "region-east": "Eastern India regional skyline illustration",
  "region-central": "Central India regional skyline illustration"
};

export const BOFU_PAGE_IMAGES: Record<string, string> = {
  "career-counselling-after-10th": "hero-school-students-parents",
  "career-counselling-benefits": "hero-school-students-parents",
  "career-counselling-benefits-for-students": "hero-school-students-parents",
  "career-counselling-for-class-10-students": "hero-school-students-parents",
  "career-counselling-for-parents": "hero-school-students-parents",
  "career-counselling-for-school-students": "hero-school-students-parents",
  "career-counselling-for-students": "hero-school-students-parents",
  "career-guidance-after-10th": "hero-school-students-parents",
  "career-guidance-for-confused-students": "hero-school-students-parents",
  "career-guidance-for-low-board-scores": "hero-school-students-parents",
  "student-career-guidance": "hero-school-students-parents",
  "career-counselling-after-12th": "hero-class-11-12",
  "career-counselling-for-11th-class-students": "hero-class-11-12",
  "career-counselling-for-12th-students": "hero-class-11-12",
  "career-guidance-after-12th": "hero-class-11-12",
  "career-guidance-after-12th-computer-science": "hero-class-11-12",
  "career-guidance-after-12th-online": "hero-class-11-12",
  "career-counselling-for-arts-students": "hero-stream-specific",
  "career-counselling-for-commerce-students": "hero-stream-specific",
  "career-counselling-for-pcb-students": "hero-stream-specific",
  "career-counselling-for-pcm-students": "hero-stream-specific",
  "career-counselling-for-neet-aspirants": "hero-stream-specific",
  "career-counselling-for-ca-aspirants": "hero-stream-specific",
  "career-coaching-for-engineering-students": "hero-graduates-college",
  "career-coaching-for-freshers": "hero-graduates-college",
  "career-coaching-for-science-students": "hero-graduates-college",
  "career-counselling-after-engineering": "hero-graduates-college",
  "career-counselling-after-graduation": "hero-graduates-college",
  "career-counselling-for-bds-graduates": "hero-graduates-college",
  "career-counselling-for-college-students": "hero-graduates-college",
  "career-counselling-for-dropouts": "hero-graduates-college",
  "career-counselling-for-engineering-students": "hero-graduates-college",
  "career-counselling-for-first-generation-graduates": "hero-graduates-college",
  "career-counselling-for-freshers": "hero-graduates-college",
  "career-counselling-for-government-exam-aspirants": "hero-graduates-college",
  "career-counselling-for-government-jobs": "hero-graduates-college",
  "career-counselling-for-low-cgpa-students": "hero-graduates-college",
  "career-counselling-for-mba-graduates": "hero-graduates-college",
  "career-counselling-for-mba-students": "hero-graduates-college",
  "career-counselling-for-nri-students": "hero-graduates-college",
  "career-counselling-for-students-with-backlogs": "hero-graduates-college",
  "career-counselling-for-study-abroad": "hero-graduates-college",
  "career-counselling-for-tier-2-college-students": "hero-graduates-college",
  "career-counselling-for-upsc-aspirants": "hero-graduates-college",
  "career-guidance-after-b-tech-ece": "hero-graduates-college",
  "career-guidance-after-bba": "hero-graduates-college",
  "career-guidance-after-bcom": "hero-graduates-college",
  "career-guidance-after-bsc": "hero-graduates-college",
  "career-guidance-after-engineering-without-placement": "hero-graduates-college",
  "career-guidance-after-gap-year": "hero-graduates-college",
  "career-coaching-for-career-change": "hero-working-professionals",
  "career-coaching-for-entrepreneurs": "hero-working-professionals",
  "career-coaching-for-it-professionals": "hero-working-professionals",
  "career-coaching-for-layoff-recovery": "hero-working-professionals",
  "career-coaching-for-mid-career-professionals": "hero-working-professionals",
  "career-coaching-for-professionals": "hero-working-professionals",
  "career-coaching-for-women": "hero-working-professionals",
  "career-counselling-for-adults": "hero-working-professionals",
  "career-counselling-for-it-professionals": "hero-working-professionals",
  "career-counselling-for-seniors": "hero-working-professionals",
  "career-counselling-for-women": "hero-working-professionals",
  "career-counselling-for-working-professionals": "hero-working-professionals",
  "career-guidance-for-30-year-olds": "hero-working-professionals",
  "career-guidance-for-women-returning-to-work": "hero-working-professionals",
  "executive-career-coaching": "hero-working-professionals",
  "professional-career-counselling": "hero-working-professionals",
  "professional-career-guidance": "hero-working-professionals",
  "working-professional-career-guidance": "hero-working-professionals",
  "career-counselling-for-adults-online": "hero-working-professionals",
  "career-coach-near-me": "hero-online-session",
  "career-coach-online": "hero-online-session",
  "career-counselling-consultation": "hero-online-session",
  "career-counselling-online": "hero-online-session",
  "career-counselling-package": "hero-online-session",
  "career-counselling-program": "hero-online-session",
  "career-counselling-service": "hero-online-session",
  "career-counselling-session": "hero-online-session",
  "career-counselling-subscription": "hero-online-session",
  "career-counselling-workshop": "hero-online-session",
  "career-development-workshop-online": "hero-online-session",
  "career-guidance-counselor": "hero-online-session",
  "career-guidance-expert-online": "hero-online-session",
  "career-guidance-online": "hero-online-session",
  "career-guidance-service": "hero-online-session",
  "career-guidance-session": "hero-online-session",
  "career-mentoring-program": "hero-online-session",
  "career-planning-session-online": "hero-online-session",
  "counselling-for-career-planning": "hero-online-session",
  "free-career-counselling-session": "hero-online-session",
  "group-career-counselling-session": "hero-online-session",
  "hire-a-career-coach": "hero-online-session",
  "one-on-one-career-coaching-session": "hero-online-session",
  "online-career-counselling-services": "hero-online-session",
  "trial-career-counselling-session": "hero-online-session",
  "virtual-career-counselling": "hero-online-session",
  "affordable-career-counselling": "hero-pricing",
  "career-counselling-cost": "hero-pricing",
  "career-counselling-fees": "hero-pricing",
  "best-career-counselling-for-students": "hero-evaluation",
  "best-career-counselling-online": "hero-evaluation",
  "best-career-counselling-platform": "hero-evaluation",
  "best-career-counsellor": "hero-evaluation",
  "best-career-guidance-website": "hero-evaluation",
  "best-online-career-guidance": "hero-evaluation",
  "best-skill-development-platform": "hero-evaluation",
  "career-counselling-questions-for-students": "hero-evaluation",
  "career-counselling-vs-career-coaching": "hero-evaluation",
  "career-guidance-platform-review": "hero-evaluation",
  "compare-career-counselling-services": "hero-evaluation",
  "top-career-coaching-services": "hero-evaluation",
  "where-to-get-career-counselling": "hero-evaluation",
  "best-career-aptitude-test": "hero-assessment",
  "best-career-assessment-platform": "hero-assessment",
  "career-counselling-psychometric-test": "hero-assessment",
  "": "hero-hub",
  "career-counselling": "hero-career-counselling",
  "career-guidance": "hero-career-guidance",
  "career-counselling-helpline": "hero-helpline-whatsapp",
  "locations": "hero-locations-hub",
  "career-counselling-in-delhi-after-10th": "hero-school-students-parents",
  "career-counselling-in-mumbai-after-10th": "hero-school-students-parents",
  "locations/career-counselling-in-delhi": "city-delhi",
  "locations/career-counselling-in-mumbai": "city-mumbai",
  "locations/career-counselling-in-bangalore": "city-bangalore",
  "locations/career-counselling-in-hyderabad": "city-hyderabad",
  "locations/career-counselling-in-chennai": "city-chennai",
  "locations/career-counselling-in-kolkata": "city-kolkata",
  "locations/career-counselling-in-pune": "city-pune",
  "locations/career-counselling-in-ahmedabad": "city-ahmedabad",
  "locations/career-counselling-in-pitampura": "city-delhi",
  "locations/career-counselling-in-paschim-vihar": "city-delhi",
  "locations/career-counselling-in-noida": "city-delhi",
  "locations/career-counselling-in-greater-noida": "city-delhi",
  "locations/career-counselling-in-gurgaon": "city-delhi",
  "locations/career-counselling-in-chembur": "city-mumbai",
  "locations/career-counselling-in-dadar": "city-mumbai",
  "locations/career-counselling-in-kalyan": "city-mumbai",
  "locations/career-counselling-in-kandivali": "city-mumbai",
  "locations/career-counselling-in-navi-mumbai": "city-mumbai",
  "locations/career-counselling-in-thane": "city-mumbai",
  "locations/career-counselling-in-agra": "region-north",
  "locations/career-counselling-in-chandigarh": "region-north",
  "locations/career-counselling-in-jaipur": "region-north",
  "locations/career-counselling-in-jalandhar": "region-north",
  "locations/career-counselling-in-kanpur": "region-north",
  "locations/career-counselling-in-kota": "region-north",
  "locations/career-counselling-in-lucknow": "region-north",
  "locations/career-counselling-in-ludhiana": "region-north",
  "locations/career-counselling-in-panchkula": "region-north",
  "locations/career-counselling-in-aurangabad": "region-west",
  "locations/career-counselling-in-goa": "region-west",
  "locations/career-counselling-in-jalgaon": "region-west",
  "locations/career-counselling-in-kolhapur": "region-west",
  "locations/career-counselling-in-nashik": "region-west",
  "locations/career-counselling-in-rajkot": "region-west",
  "locations/career-counselling-in-surat": "region-west",
  "locations/career-counselling-in-vadodara": "region-west",
  "locations/career-counselling-in-coimbatore": "region-south",
  "locations/career-counselling-in-trivandrum": "region-south",
  "locations/career-counselling-in-kochi": "region-south",
  "locations/career-counselling-in-kozhikode": "region-south",
  "locations/career-counselling-in-thrissur": "region-south",
  "locations/career-counselling-in-visakhapatnam": "region-south",
  "locations/career-counselling-in-bhubaneswar": "region-east",
  "locations/career-counselling-in-ranchi": "region-east",
  "locations/career-counselling-in-siliguri": "region-east",
  "locations/career-counselling-in-guwahati": "region-east",
  "locations/career-counselling-in-bhopal": "region-central",
  "locations/career-counselling-in-jabalpur": "region-central",
  "locations/career-counselling-in-nagpur": "region-central",
  "locations/career-counselling-in-raipur": "region-central"
};
