// Stage-specific additions for the self-rating tests in skillSelfTests.ts:
// extra statements asked only at certain stages, and advice written for each
// stage and score area. General guidance only: no statistics, norms or hiring claims.
import type { SkillTestId } from './skillSelfTests';

export type ExtraQuestion = { d: string; text: string; stages: string[]; tip: string; up?: string; reverse?: boolean };
export type StageAdvice = { situation: string; actions: string[] };

const x = (stages: string[], d: string, text: string, tip: string, up: string, reverse = false): ExtraQuestion =>
  reverse ? { d, text, stages, tip, up, reverse } : { d, text, stages, tip, up };

export const EXTRA_QUESTIONS: Record<SkillTestId, ExtraQuestion[]> = {
  'confused-after-10th': [
    x(['before'], 'self', 'I have noticed which topics I read about or watch without anyone asking me to.', 'Keep a short note for a week of what you read or watch by choice. Topics that repeat are real interest signals.', 'Add a column for how long you spent and whether anyone asked you to. Pick the top two topics and try a small task in each this week.'),
    x(['before'], 'options', 'I know which routes stay open to me whatever my board marks turn out to be.', 'List which routes need a minimum mark and which do not, such as skill courses or open schooling, so one result never feels like the end of the road.', 'Check two of those routes on an official page and write the mark rule with its source. Update the list once results are out.'),
    x(['before'], 'pressure', 'I can talk about my plans with my family without feeling I must already have the final answer.', 'Tell your family you are still exploring and will bring two or three options to compare once results are out.', 'Fix a time this week for a ten-minute family talk about your options, and bring a one-page list of two or three routes.'),
    x(['before'], 'action', 'I keep telling myself I will think about all this only after the results come out.', 'After your last paper, fix one hour on three evenings for one task each: read about one route, speak to one person, try one small project. Results then confirm a short list instead of starting from nothing.', 'Move one of those evening tasks to this week. When you catch the "after results" thought, ask what you could do in ten minutes today.', true),
    x(['choosing'], 'options', 'I know the eligibility rules and last dates for the schools or courses I am considering.', 'Open the official website of each board or institute you are considering and write down eligibility, fees and last dates in one place.', 'Record each date in a calendar with a reminder a week ahead. Ask the institute\'s office to confirm any rule you are unsure of.'),
    x(['choosing'], 'process', 'I have compared at least two options on the same points, such as subjects, cost, travel and what each leads to.', 'Make a small table with the same rows for each option. Comparing on the same points exposes what a feeling hides.', 'Add a column for evidence in each row, such as a link or a person\'s name. Ask a teacher to point out any row that has none.'),
    x(['choosing'], 'pressure', 'I am leaning towards this stream mainly because my closest friends are taking it.', 'Imagine every friend choosing something else. If your choice changes, write down what you like about the stream itself and what you only like about the company.', 'Write each friend\'s reason next to your own and underline the ones that are not yours. Talk to one student outside your friend group who took the same stream.', true),
    x(['choosing'], 'action', 'I know whom to ask, at school or at home, for the exact admission steps.', 'Name one person at school and one at home who can confirm admission steps and dates, and ask them this week.', 'Save their contact or office timing in your phone and note the date you will ask. After the answer, write the steps in order with a date for each.'),
    x(['chosen'], 'self', 'I can say in one sentence why I picked my stream or course.', 'Write that sentence down. If it is only "everyone took it", spend time finding one real reason, because it will carry you through hard months.', 'Say the sentence to a family member and see if it still holds. Review it again after your first term\'s tests.'),
    x(['chosen'], 'options', 'I know what I can do later if this choice turns out wrong, such as switching, adding a course or building a skill.', 'Learn the actual switching and bridging options for your board. Knowing the exit makes a wrong turn recoverable.', 'Ask a teacher or counsellor to confirm each exit in your list and write the last date for each switch. Keep the list where you can find it.'),
    x(['chosen'], 'process', 'I will judge whether this choice suits me only by my next exam marks.', 'Marks are one sign among several. Add two more, such as how much free time you spend on the subject by choice and how you feel before class, and review all three on a set date.', 'Set the review date now and write the three signs on one page. When a test result arrives, check the other two signs before you react.', true),
    x(['chosen'], 'action', 'I have started building at least one skill beyond the syllabus that fits where I am heading.', 'Choose one small skill linked to your direction, such as typing, basic Excel or a language, and practise it for twenty minutes on four days a week. Something you can show is useful beyond marks.', 'Show a small piece of that skill, such as a typed page or a sheet, to a teacher or senior each month. Ask for one improvement and apply it the next week.'),
  ],
  communication: [
    x(['school'], 'listen', 'After a teacher explains something, I can say the main point in one line.', 'After each class, write the teacher\'s main point in one line. If you cannot, ask a friend or the teacher the next day.', 'Share your one-line summary with a friend each day for a week and compare. Where the two differ, ask the teacher the next day.'),
    x(['school'], 'speak', 'I can answer a teacher\'s question in two or three clear sentences.', 'Practise answers in a fixed order: the answer first, then one reason, then one example.', 'Time your answer aloud and aim for under thirty seconds. Ask a family member whether the answer came first.'),
    x(['school'], 'write', 'I start writing an answer or letter before I know what my main point is.', 'Before writing, note one line each for what you will say, your support for it, and how you will close.', 'After writing, underline your main point. If it is not in the first two lines, move it up. Do this for a week on homework answers.', true),
    x(['school'], 'present', 'I put my hand up to speak in class or at school events.', 'Take one small speaking task, such as reading an announcement, and add a slightly bigger one each month.', 'Set a target of speaking once in each class this week. Note which subject felt easiest and start there.'),
    x(['college'], 'listen', 'In group projects I make sure I understand the task before I suggest solutions.', 'Restate the task in one sentence and ask the group to confirm it before you discuss how to do it.', 'After the group agrees, write the task and each person\'s part in the group chat. Check at the halfway point whether anyone\'s understanding has changed.'),
    x(['college'], 'speak', 'I can explain my project to a classmate or senior in under two minutes.', 'Time yourself explaining your project. Cut it until the main idea comes within the first twenty seconds.', 'Explain it to a classmate from another branch and ask them to repeat it back. Cut anything they could not repeat.'),
    x(['college'], 'write', 'When I email a professor or placement officer, I say clearly what I need in the first line.', 'Use a clear subject line, one request in the first line, and details after it. Read it once as if you were the person receiving it.', 'Ask a senior or friend to read only your subject line and first sentence, and say what you want. Rewrite until they can say it.'),
    x(['college'], 'feedback', 'I argue with review or viva comments on my project before I have understood them.', 'When you get a comment, write it down, ask one question to clarify what is wanted, and thank the person. Decide your answer after that.', 'When you feel the urge to argue, note the comment and wait a day before replying. Start your reply with what you agree with, then ask your question.', true),
    x(['fresher'], 'speak', 'I have a short introduction ready that I can say in about 30 seconds.', 'Prepare it in three parts: your background, your strongest skill with one example, and the kind of role you want. Say it aloud until it feels natural.', 'Say your introduction to two different people this week and ask each for one unclear part. Adjust it, and keep a fifteen-second version too.'),
    x(['fresher'], 'write', 'My resume lines show something I did, such as a project, task or number, not just words like "hardworking".', 'Replace each general word with one example of what you did and what changed because of it.', 'Check each line for a verb, a task and a result. Ask a senior to underline the line that tells them the least.'),
    x(['fresher'], 'present', 'When an interviewer asks an unexpected follow-up, my mind goes blank.', 'Practise with a friend who asks "why" and "how" after every answer. Pause for a breath, then answer one point at a time.', 'When you blank, say "Let me think for a moment", take a breath and give one point. Practise this pause in every mock interview.', true),
    x(['fresher'], 'feedback', 'After a rejection or a task, I ask what I could do better.', 'Send a short, polite message asking for one thing to improve. Some people will not reply, but those who do give useful points.', 'Keep a note of each improvement point you received and what you changed. Read the list before your next interview or task.'),
    x(['professional'], 'listen', 'In meetings I can summarise what was decided and who does what.', 'End each meeting with a two-line recap of decisions and owners, and send it in writing.', 'At the next meeting, check whether others agree with your recap, and fix any gaps the same day. Keep all recaps in one folder.'),
    x(['professional'], 'speak', 'I can explain a technical or complex point to a colleague or client who is not an expert.', 'Explain it with one comparison from daily life and one concrete example, then ask what is still unclear.', 'Ask the listener to explain it back and note where your meaning changed. Keep the best comparison for future use.'),
    x(['professional'], 'write', 'People can act on my status updates without asking me for more details.', 'Structure updates as: what is done, what is next, what you need and by when.', 'Ask one regular recipient which update needed a follow-up question last month. Add that missing item to your template.'),
    x(['professional'], 'feedback', 'I say yes to deadlines that I know are not realistic.', 'Name the constraint, say what it affects, and offer one alternative date or smaller scope instead of only saying yes or no.', 'When you hear yourself about to say yes, ask for a ten-minute pause. Check the real effort and reply with a date you can meet.', true),
  ],
  'soft-skills': [
    x(['school'], 'team', 'In a group assignment I check whether my teammates are stuck.', 'At the midpoint, ask each teammate one question: "Do you need anything from me to finish your part?" A two-minute check prevents last-minute gaps.', 'Do the check at the midpoint and again two days before the due date. Write what each teammate needed and whether it was done.'),
    x(['school'], 'own', 'I need a parent or teacher to remind me before I submit homework and projects.', 'Write every due date on one page of your notebook and put your own date a day earlier next to it. Look at the page each evening, so the reminder comes from you, and tick each item when submitted.', 'Check the page at the same time every evening and mark a tick or a note beside each item. Do this for two weeks without reminders from home.', true),
    x(['school'], 'adapt', 'When a subject or teacher changes, I adjust my study method instead of giving up.', 'Try a different way of studying for a week, such as notes, practice questions or teaching a friend, and keep what works.', 'After a week with the new method, compare one test score or practice result with the old method and keep the better one.'),
    x(['school'], 'solve', 'When I do not understand a topic, I try another resource before asking for the answer.', 'Try one other source, such as a video or a different book, then ask a specific question about what is still unclear.', 'Write down the resource you tried and what it did and did not explain. Show that note when you ask your question.'),
    x(['college'], 'lead', 'In a club or project I have taken responsibility for something others depended on.', 'Take one small task that others rely on in a club or project, and complete it visibly. That is leadership evidence.', 'Ask one group member how reliable you were and write the answer down. It can become a line on your resume.'),
    x(['college'], 'team', 'In group projects I stay quiet when the workload is uneven.', 'Raise it within the first week, with a suggestion for how to split the work, rather than waiting until it builds into a conflict. Say it as a question, such as "Can we rebalance the tasks?"', 'Note each person\'s tasks in the first meeting so the split is visible. If it is uneven, raise it then with a suggestion to rebalance.', true),
    x(['college'], 'own', 'I spread my deadlines across subjects instead of leaving everything for the last day.', 'List all deadlines for the term and set a personal start date for each, working back from the due date.', 'Share the plan with a friend who will ask on the start date. Check your progress at the halfway point of each deadline.'),
    x(['college'], 'adapt', 'This year I have taken up something outside my course, such as a skill, a club role or an event.', 'Choose one activity beyond your syllabus, tell a friend you will do it, and keep to it for a full term. Note what you learned from it each month.', 'Add a monthly review: write one thing learnt and one thing to change. Keep one result, such as a poster or certificate, to show at the end of the term.'),
    x(['fresher'], 'own', 'In an internship or first job I follow up on tasks without waiting to be asked.', 'Close the loop on each task: tell the person it is done, share the result and ask whether anything else is needed.', 'Keep a log of each task closed, with the date and the person told. Review it every Friday to find tasks where the message came late.'),
    x(['fresher'], 'adapt', 'I can learn a new tool or process quickly in a new team.', 'In the first days of a new role, write down the tools and processes used and learn the most frequent ones first.', 'Make a one-page guide of the steps of the commonest tool and ask a senior to correct it. Use it for a month.'),
    x(['fresher'], 'team', 'I ask colleagues for help without saying what I have already tried.', 'Before asking, write two lines: what you tried and the exact thing you need. A specific, short question gets a faster and better answer.', 'Keep a template of those two lines in your notes and fill it before every question. After a week, see which questions got the fastest reply.', true),
    x(['fresher'], 'solve', 'When a task is unclear, I clarify the goal first and then start.', 'Write what done looks like in two lines and confirm it with the person who gave the task.', 'Write the done line before starting and check it against the result at the end. Note once a week where the goal changed midway.'),
    x(['professional'], 'lead', 'I find it hard to hand work over because I feel I must do it myself.', 'Next time you hand over a task, state the outcome, the deadline and a check-in point, then follow up at that point instead of redoing the work.', 'At each check-in, ask one question about progress and leave their work alone. Write what you would have changed and see whether it mattered.', true),
    x(['professional'], 'team', 'I can work across teams where I have no authority.', 'Build agreement on a shared goal first, and show what each side gains before you ask for effort.', 'List the people you need and their goals, and give each a clear benefit in your next request. Review each month who responded and why.'),
    x(['professional'], 'adapt', 'I stay effective during reorganisations, new tools or changes in my role.', 'List what is changing and what is not, and pick one new capability the change lets you build.', 'Share your list of changes with a colleague and ask what they see differently. Fix a date by which you will test the new capability.'),
    x(['professional'], 'solve', 'Before I start my week, I sort my tasks into urgent and important.', 'Spend ten minutes on Monday morning marking each task as urgent, important, both or neither. Then hand over, delay or drop the ones marked neither.', 'Ask a manager or peer to rank your list for one week. Compare the ranking with how your day went and adjust the following Monday.'),
  ],
};

const sa = (situation: string, a: string, b: string): StageAdvice => ({ situation, actions: [a, b] });

export const STAGE_ADVICE: Record<SkillTestId, Record<string, Record<string, StageAdvice>>> = {
  'confused-after-10th': {
    before: {
      self: sa('Before results, you do not need a final answer, but you do need evidence about yourself.', 'Note which subjects you pick up first when you have free time and which tasks make time pass quickly.', 'Ask one teacher and one family friend what they have seen you do well, and compare with your own list.'),
      options: sa('Before results, learning the options costs nothing and keeps you ready for any outcome.', 'Read what each of Science, Commerce, Arts, diploma and ITI involves for the next two years, one page per route.', 'Find out which routes are open to you at different mark levels so you are not surprised on result day.'),
      pressure: sa('Before results, family opinions are loud and your own view is still forming.', 'Share your shortlist of two or three routes with your family and ask them to compare them with you, not pick for you.', 'Write your reasons for each route so that the conversation is about reasons, not about who is more certain.'),
      process: sa('Before results, a method helps you decide calmly once marks arrive.', 'Choose three or four points to judge every option on, such as subjects, cost, where it leads and what you enjoy.', 'Agree in advance with yourself that you will decide within a set period after results rather than waiting for a perfect answer.'),
      action: sa('Before results, small actions beat waiting.', 'Do one exploration task a week: read, watch, or speak to someone doing the work you are curious about.', 'Keep your study hours for the remaining papers protected, and do the exploring in the gaps.'),
    },
    choosing: {
      self: sa('With results out, your marks are one fact; your interests and strengths are the others.', 'Match your strongest two or three subjects and tasks to the routes you are weighing, and note where they agree.', 'Treat the choice as a direction you can adjust, not as a lock for life.'),
      options: sa('With results out, the gap is usually exact rules, not general ideas.', 'Check eligibility, fees, dates and seat rules on the official page of every route you shortlist.', 'Speak to someone who has done each route and ask what they would do differently.'),
      pressure: sa('At the point of choosing, others\' opinions can drown out your reasons.', 'Hold one calm conversation with your family where you present your top two options and your reasons for each.', 'Ask what worries them specifically, then find facts that address each worry.'),
      process: sa('Choosing needs a way to decide, not a wait for certainty.', 'Score each shortlisted route on the same points, then sleep on the result before you decide.', 'Pick the option that is good on your points and recoverable if wrong, instead of waiting for the perfect one.'),
      action: sa('The decision window is real, so convert thinking into steps.', 'Write the next three actions, such as documents, forms and conversations, each with a date.', 'Do the first one today so the decision starts moving.'),
    },
    chosen: {
      self: sa('Having chosen, understanding yourself helps you choose subjects and skills inside the route.', 'Notice what you enjoy inside your route and use it to pick optional subjects, projects and skills.', 'Once a term, list three tasks you enjoyed and three you dreaded in your route, and compare with the last list.'),
      options: sa('Having chosen, the useful question is where your route leads and what can be added to it.', 'Map three possible careers from your route and the skills each one asks for.', 'Learn the bridging and switching options so you know your choice is not a trap.'),
      pressure: sa('Having chosen, others\' views continue, and you need a steady answer to them.', 'Prepare a short, calm explanation of your choice and plan, and use it each time the topic comes up.', 'Share your first test results with the family, along with what you plan to change, so the talk stays about evidence.'),
      process: sa('Having chosen, a review habit keeps the decision honest.', 'Set a review date and check your three signs, for example marks trend, time spent by choice and how you feel before tests.', 'Adjust early with small changes, such as subjects, study methods or added skills, before a big change is needed.'),
      action: sa('Having chosen, momentum comes from small, visible steps.', 'Pick one skill beyond the syllabus that fits your direction and practise it regularly.', 'Keep a simple record of what you finish, so proof builds without extra effort.'),
    },
  },
  communication: {
    school: {
      listen: sa('At school, most of what you learn arrives by listening, and a point missed in class becomes a gap in the exam.', 'Before you leave each class, write the teacher\'s main point in one line, and compare it with a classmate\'s.', 'This week, say back to a friend what they told you in your own words, once, to check you got it.'),
      speak: sa('At school, you are asked short questions all day, and a clear first sentence makes an answer sound confident.', 'Practise last week\'s homework questions aloud with the answer first, then one reason, then one example.', 'Once a week, say a one-minute answer to a family member and count how often you say "umm".'),
      write: sa('At school, clear writing earns marks in every subject, not only in languages.', 'Before each long answer or letter, jot three lines: what you will say, your proof, and how you will end.', 'Pick one old answer where marks were cut for being unclear and rewrite it with the main point in the first sentence.'),
      feedback: sa('At school, correction from teachers and honest talk with friends are your fastest feedback.', 'When a teacher corrects you, ask "what should I do differently next time?" instead of explaining why you wrote it.', 'Tell a friend one kind, specific thing about their work this week, such as which part of their answer was clear.'),
      present: sa('At school, assemblies, quizzes and class presentations are low-risk places to practise speaking.', 'Begin with a one-minute talk to three friends, then repeat it for a bigger group the next week.', 'Practise standing up with a timer before any presentation, since reading silently does not train your voice.'),
    },
    college: {
      listen: sa('In college, group projects fail more often from a misunderstood task than from lack of ability.', 'At the first meeting, restate the task and each person\'s part in one minute and ask the group to confirm.', 'Keep a pen ready for your questions and ask them when the speaker pauses, instead of cutting in.'),
      speak: sa('In college, you explain your work in vivas, seminars and placement rounds.', 'Explain your latest project to someone from another branch and note where their face goes blank.', 'Prepare a 30-second version and a two-minute version of each project and keep both in your notes.'),
      write: sa('In college, your emails and reports are read by teachers, seniors and recruiters who may not know you.', 'Rewrite one email with a clear subject line, the request in the first line and details underneath.', 'Ask a senior to look at your resume and one message, and ask which line they understood least.'),
      feedback: sa('In college, reviews and vivas show how you handle correction in front of others.', 'After each review, list every comment and write one action beside each before you talk to anyone about it.', 'Disagree once this month in a group discussion, giving a reason, and notice whether the tone stayed friendly.'),
      present: sa('In college, seminars and group discussions are rehearsal for placement rounds.', 'Present in a class, club or department event regularly, even for three minutes, so speaking feels normal.', 'Form a practice group of four friends and review each other\'s opening lines in a group discussion.'),
    },
    fresher: {
      listen: sa('As a fresher, interviewers and seniors often give an instruction once, and one missed detail costs you.', 'Use the key words of an interview question in your first sentence so you answer what was asked.', 'When a senior gives you a task, repeat the deliverable and deadline back and write both down before you leave.'),
      speak: sa('As a fresher, your spoken answers carry much of your interview.', 'Prepare three short stories from projects, internships or college work, each saying what you did and what came of it.', 'Practise them aloud with a friend who raises a hand whenever you wander from the point.'),
      write: sa('As a fresher, your resume and first messages are how employers meet you.', 'Rewrite each resume line to show an action and its result, such as "ran the registration desk for the college fest".', 'Fit each application message to its role by using truthful words from the job description.'),
      feedback: sa('As a fresher, how you take correction shows seniors whether you are easy to teach.', 'After each task in an internship or trial, ask your senior for one thing to improve and note the change you will make.', 'After a rejection, send a polite two-line message asking for one improvement point, and accept that some will not reply.'),
      present: sa('As a fresher, presenting appears in interviews, assessments and training sessions.', 'Prepare a five-minute and a three-minute talk on your best project, so you can fit the time you are given.', 'List the five questions you fear most about that project and practise a short, calm answer to each.'),
    },
    professional: {
      listen: sa('As a working professional, rework from misheard requests is among the most avoidable time losses.', 'Before starting a request, send the sender one line saying what you understood and by when you will deliver.', 'Send a two-line recap of decisions and owners within the day after each meeting you attend.'),
      speak: sa('As a working professional, how clearly you speak decides how quickly others act.', 'Lead with the conclusion in meetings, then give two supporting points and stop.', 'Before explaining to a client or another team, pick one everyday comparison for the technical part.'),
      write: sa('As a working professional, your writing works for you when you are not in the room.', 'Use one structure for every update: done, next, need, by when.', 'Delete any sentence in an email that does not help the receiver decide or act.'),
      feedback: sa('As a working professional, timely feedback and honest pushback affect trust and workload.', 'Give feedback within a day of the event, naming the action and what happened because of it.', 'When you disagree, bring your concern together with one alternative the other person can say yes to.'),
      present: sa('As a working professional, you present in reviews, client calls and team updates.', 'Structure each talk as problem, options, your recommendation and what you need from them.', 'Practise your opening line and your answer to the toughest likely question, out loud, the day before.'),
    },
  },
  'soft-skills': {
    school: {
      lead: sa('At school, leadership starts with small responsibilities, not with being class captain.', 'Offer to run one small thing, such as a revision group of three or four friends for one week, and set the topic for each day.', 'At the end of the week, ask one friend what you did well as organiser and what to change.'),
      team: sa('At school, teamwork is learnt in group assignments, practicals and sports.', 'In your next group task, ask each person which part they want before you pick yours, and write the split on one sheet.', 'This week, tell one teammate exactly what they did that helped.'),
      adapt: sa('At school, a new subject, teacher or medium of instruction tests how you adapt.', 'When something changes, list what you control, such as your notes and practice time, and start with the first item.', 'Try one new study method for a week, such as teaching a friend, and keep it only if your confidence or test result improves.'),
      own: sa('At school, reliability begins with homework and promises to friends.', 'Keep a notebook page of commitments with dates and tick each one the day it is done.', 'If you cannot keep a promise to a friend, say so the same day and offer another time.'),
      solve: sa('At school, problem solving grows by trying before asking.', 'Before asking a teacher, write what you tried and the exact step where you got stuck.', 'Split a hard question into two parts and finish the first part before looking at the answer.'),
    },
    college: {
      lead: sa('In college, clubs, events and projects are where leadership becomes visible.', 'Take one deliverable in a project, such as the poster, the budget or the schedule, and finish it a day before it is due.', 'After the event, ask two group members one thing you could do better in coordinating.'),
      team: sa('In college, team projects are your best rehearsal for the workplace.', 'At the first meeting, write roles and deadlines on one page and ask everyone to confirm them.', 'If the workload is uneven, raise it within a week with a suggested split, not after the submission.'),
      adapt: sa('In college, changing electives, syllabus and campus life reward flexibility.', 'Learn one tool outside the syllabus, such as a spreadsheet function or basic photo editing, for thirty minutes a day over two weeks.', 'When a plan fails, write one change to try and do it within the same week.'),
      own: sa('In college, reliability shows in how you handle internal deadlines and lab records.', 'Put every submission date of the term in a calendar, with your own date two days earlier.', 'If you will miss a date, tell the faculty before it passes and propose a new one.'),
      solve: sa('In college, projects reward structured problem solving.', 'Write the problem, two options and your choice in three lines before you build anything.', 'After each project, write three lines on what you would do differently and keep them in one file.'),
    },
    fresher: {
      lead: sa('As a fresher, leadership means owning your piece and helping others.', 'Take one small task and own it fully, with a short update to your lead every second day.', 'Offer to show a newer colleague or intern one thing you learned this month.'),
      team: sa('As a fresher, being easy to work with matters as much as skill.', 'In your first month, note how each teammate likes to get updates, by chat, call or in writing, and use that.', 'In your updates, name who helped you and what they did.'),
      adapt: sa('As a fresher, new tools and teams come fast.', 'List the tools used in your first weeks and learn the most used ones first, twenty minutes a day.', 'Ask a colleague for a fifteen-minute walk-through, then practise on a small task the same day.'),
      own: sa('As a fresher, reliability is how you earn bigger tasks.', 'Confirm the deadline in writing when you accept a task, and deliver on or before that day.', 'When a task is done, send two lines saying what is done and where to find it.'),
      solve: sa('As a fresher, showing you tried before asking builds respect.', 'Before you ask, write the problem, what you tried and one question, in three lines.', 'Keep a personal notebook of fixes and where you found them, so you do not ask the same thing twice.'),
    },
    professional: {
      lead: sa('As a professional, leadership shows in clarity, delegation and accountability.', 'Whenever you assign work, state the goal, how success will be judged and the date in one message.', 'Every quarter, ask each team member in a short one-to-one what you could do to make their work easier.'),
      team: sa('As a professional, cross-team work is a main source of impact.', 'Before asking another team for help, find out what they are measured on and show how your request helps them.', 'Fix a fifteen-minute fortnightly check-in with the two partners you depend on most.'),
      adapt: sa('As a professional, changes in tools, roles and managers come regularly.', 'When a change is announced, write what changes, what stays and one new capability it lets you build.', 'Keep a short list of what is stable, such as your core skills and key clients, to anchor you.'),
      own: sa('As a professional, ownership shapes how much trust people place in you.', 'Track every commitment in one system and review it on a fixed day each week.', 'Flag a risk on the day you see it, with a proposed fix and a date.'),
      solve: sa('As a professional, structured problem solving is a core skill.', 'Use a repeatable method: define the problem, list causes, test the likeliest and write the result.', 'Share what you learned in a short note to the team so others avoid the same loop.'),
    },
  },
};

export const PARENT_SECTION = {
  'confused-after-10th': {
    title: 'If you are a parent or guardian reading this result',
    body: [
      'The result is based only on your child\'s own ratings. Use it as a conversation starter, not as a verdict.',
      'Look at the lowest area first. If it is "Pressure from others", the most useful thing you can do is listen to your child\'s reasons before sharing your own.',
      'If it is "Knowing the options", sit together and read the official pages for two or three routes, so the facts come from the same source for both of you.',
      'Agree on a date to decide, and agree that the choice can be reviewed after a few months, so no one feels trapped.',
    ],
  },
} as Partial<Record<SkillTestId, { title: string; body: string[] }>>;
